# Generated by Django 2.2.1 on 2019-05-08 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pascal', '0002_auto_20190508_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
